import type { DatabaseAdapter } from "@/database/types";

/**
 * First-launch seed from the bundled master data (public/master-data-bundle.json,
 * generated by scripts/build-master-bundle.mjs).
 *
 * Rules:
 * - Seeds ONLY into empty local tables — it is a cold-start floor, never an
 *   overwrite of data the user or the sync layer already produced.
 * - Seeded rows carry a `bundle:` id prefix; the first successful full network
 *   refresh clears the table before writing live rows (see bootstrapCache /
 *   useLocalFirstProducts), which retires the seed automatically.
 * - Failure is always non-fatal: no bundle file (dev build without the
 *   generator run) or a broken fetch simply skips seeding.
 */

const SEED_META_KEY = "bundle.seededVersion";

interface MasterDataBundle {
  version: number;
  generatedAt: string;
  products: Array<Record<string, unknown> & { id: string }>;
  customers: Array<Record<string, unknown> & { id: string }>;
  salesmen: Array<Record<string, unknown> & { id: string }>;
  brands: Array<Record<string, unknown> & { id: string }>;
}

export interface BundleSeedResult {
  status: "seeded" | "skipped" | "unavailable";
  seeded?: { products: number; customers: number; salesmen: number; brands: number };
}

export async function seedFromBundleIfEmpty(db: DatabaseAdapter): Promise<BundleSeedResult> {
  try {
    const already = await db.get<{ key: string; value: number }>("meta", SEED_META_KEY);
    if (already) return { status: "skipped" };

    // Only a truly cold store gets seeded — any products (from a previous
    // bootstrap or an earlier session) means the local store is alive.
    const productCount = await db.count("products");
    if (productCount > 0) {
      await db.put("meta", { key: SEED_META_KEY, value: -1 });
      return { status: "skipped" };
    }

    const base = (import.meta as any).env?.BASE_URL ?? "/";
    const response = await fetch(`${base}master-data-bundle.json`, { cache: "no-cache" });
    if (!response.ok) return { status: "unavailable" };

    const bundle = (await response.json()) as MasterDataBundle;
    if (!Array.isArray(bundle.products)) return { status: "unavailable" };

    const stamp = Date.now();
    const mark = (rows: Array<Record<string, unknown>>) =>
      rows.map((r) => ({ ...r, _syncedAt: stamp, _source: "bundle" }));

    await db.bulkPut("products", mark(bundle.products));
    await db.bulkPut("customers", mark(bundle.customers));
    await db.bulkPut("salesmen", mark(bundle.salesmen));
    await db.bulkPut("brands", mark(bundle.brands));
    await db.put("meta", { key: SEED_META_KEY, value: bundle.version });

    return {
      status: "seeded",
      seeded: {
        products: bundle.products.length,
        customers: bundle.customers.length,
        salesmen: bundle.salesmen.length,
        brands: bundle.brands.length,
      },
    };
  } catch {
    return { status: "unavailable" };
  }
}
